=== raml-apis/Bufferapp/schemas/newUpdate-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "success" : {
      "type" : "boolean" ,
      "required" : false
    } ,
    "buffer_count" : {
      "type" : "number" ,
      "required" : false
    } ,
    "buffer_percentage" : {
      "type" : "number" ,
      "required" : false
    } ,
    "updates" : {
      "type" : "array" ,
      "required" : false ,
      "items" : 
        {
          "type" : "object" ,
          "properties" : {
            "id" : {
              "type" : "string" ,
              "required" : false
            } ,
            "created_at" : {
              "type" : "number" ,
              "required" : false
            } ,
            "day" : {
              "type" : "string" ,
              "required" : false
            } ,
            "due_at" : {
              "type" : "number" ,
              "required" : false
            } ,
            "due_time" : {
              "type" : "string" ,
              "required" : false
            } ,
            "media" : {
              "type" : "object" ,
              "required" : false ,
              "properties" : {
                "link" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "title" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "description" : {
                  "type" : "string" ,
                  "required" : false
                }
              }
            } ,
            "profile_id" : {
              "type" : "string" ,
              "required" : false
            } ,
            "profile_service" : {
              "type" : "string" ,
              "required" : false
            } ,
            "status" : {
              "type" : "string" ,
              "required" : false
            } ,
            "text" : {
              "type" : "string" ,
              "required" : false
            } ,
            "text_formatted" : {
              "type" : "string" ,
              "required" : false
            } ,
            "user_id" : {
              "type" : "string" ,
              "required" : false
            } ,
            "via" : {
              "type" : "string" ,
              "required" : false
            }
          }
        }
      
    }
  }
}

=== raml-apis/Bufferapp/examples/newUpdate-example.json
{
  "success" : true ,
  "buffer_count" : 10 ,
  "buffer_percentage" : 20 ,
  "updates" : [
    {
      "id" : "4ecda256512f7ee521000004" ,
      "created_at" : 1320703582 ,
      "day" : "Saturday 26th November" ,
      "due_at" : 1320742680 ,
      "due_time" : "11:05 am" ,
      "media" : {
        "link" : "http://google.com" ,
        "title" : "Google" ,
        "description" : "The google homepage"
      } ,
      "profile_id" : "4eb854340acb04e870000010" ,
      "profile_service" : "twitter" ,
      "status" : "buffer" ,
      "text" : "This is an example update" ,
      "text_formatted" : "This is an example update" ,
      "user_id" : "4eb9276e0acb04bb81000067" ,
      "via" : "api"
    } , {
      "id" : "4ecda256512f7ee521000004" ,
      "created_at" : 1320703582 ,
      "day" : "Saturday 26th November" ,
      "due_at" : 1320742680 ,
      "due_time" : "11:05 am" ,
      "media" : {
        "link" : "http://google.com" ,
        "title" : "Google" ,
        "description" : "The google homepage"
      } ,
      "profile_id" : "4eb854340acb04e870000010" ,
      "profile_service" : "twitter" ,
      "status" : "buffer" ,
      "text" : "This is an example update" ,
      "text_formatted" : "This is an example update" ,
      "user_id" : "4eb9276e0acb04bb81000067" ,
      "via" : "api"
    }
  ]
}
