=== raml-apis/Bufferapp/schemas/update-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "id" : {
      "type" : "string" ,
      "required" : false
    } ,
    "created_at" : {
      "type" : "number" ,
      "required" : false
    } ,
    "day" : {
      "type" : "string" ,
      "required" : false
    } ,
    "due_at" : {
      "type" : "number" ,
      "required" : false
    } ,
    "due_time" : {
      "type" : "string" ,
      "required" : false
    } ,
    "profile_id" : {
      "type" : "string" ,
      "required" : false
    } ,
    "profile_service" : {
      "type" : "string" ,
      "required" : false
    } ,
    "sent_at" : {
      "type" : "number" ,
      "required" : false
    } ,
    "service_update_id" : {
      "type" : "string" ,
      "required" : false
    } ,
    "statistics" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "reach" : {
          "type" : "number" ,
          "required" : false
        } ,
        "clicks" : {
          "type" : "number" ,
          "required" : false
        } ,
        "retweets" : {
          "type" : "number" ,
          "required" : false
        } ,
        "favorites" : {
          "type" : "number" ,
          "required" : false
        } ,
        "mentions" : {
          "type" : "number" ,
          "required" : false
        }
      }
    } ,
    "status" : {
      "type" : "string" ,
      "required" : false
    } ,
    "text" : {
      "type" : "string" ,
      "required" : false
    } ,
    "text_formatted" : {
      "type" : "string" ,
      "required" : false
    } ,
    "user_id" : {
      "type" : "string" ,
      "required" : false
    } ,
    "via" : {
      "type" : "string" ,
      "required" : false
    }
  }
}

=== raml-apis/Bufferapp/examples/update-example.json
{
  "id" : "4eb8565e0acb04bb82000004" ,
  "created_at" : 1320703582 ,
  "day" : "Monday 7th November" ,
  "due_at" : 1320742680 ,
  "due_time" : "10:09 pm" ,
  "profile_id" : "4eb854340acb04e870000010" ,
  "profile_service" : "twitter" ,
  "sent_at" : 1320744001 ,
  "service_update_id" : "133667319959392256" ,
  "statistics" : {
    "reach" : 2460 ,
    "clicks" : 56 ,
    "retweets" : 20 ,
    "favorites" : 1 ,
    "mentions" : 1
  } ,
  "status" : "sent" ,
  "text" : "This is just the beginning, the very beginning, of the transfor..." ,
  "text_formatted" : "This is just the beginning, the very beginning, of th..." ,
  "user_id" : "4eb9276e0acb04bb81000067" ,
  "via" : "chrome"
}
