=== raml-apis/Bufferapp/schemas/user-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "_id" : {
      "type" : "string" ,
      "required" : false
    } ,
    "activity_at" : {
      "type" : "number" ,
      "required" : false
    } ,
    "created_at" : {
      "type" : "number" ,
      "required" : false
    } ,
    "id" : {
      "type" : "string" ,
      "required" : false
    } ,
    "plan" : {
      "type" : "string" ,
      "required" : false
    } ,
    "referral_link" : {
      "type" : "string" ,
      "required" : false
    } ,
    "referral_token" : {
      "type" : "string" ,
      "required" : false
    } ,
    "secret_email" : {
      "type" : "string" ,
      "required" : false
    } ,
    "timezone" : {
      "type" : "string" ,
      "required" : false
    }
  }
}

=== raml-apis/Bufferapp/examples/user-example.json
{
  "_id" : "4f0c0a06512f7ef214000000" ,
  "activity_at" : 1343654640 ,
  "created_at" : 1326189062 ,
  "id" : "4f0c0a06512f7ef214000000" ,
  "plan" : "free" ,
  "referral_link" : "http://bufferapp.com/r/abcde" ,
  "referral_token" : "abcde" ,
  "secret_email" : "buffer-abc123def456@to.bufferapp.com" ,
  "timezone" : "Asia/Tel_Aviv"
}
